export const supportedLanguages = { // eslint-disable-line
  afrikaans: { transliteration: false, localName: null },
  arabic: true,
  mandarin: { transliteration: true, localName: '中文' },
  cantonese: true,
  czech: false,
  danish: false,
  dutch: false,
  finnish: false,
  french: false,
  german: false,
  greek: { transliteration: true, localName: 'ελληνικά' },
  hebrew: true,
  hindi: true,
  hungarian: false,
  italian: false,
  japanese: true,
  khmer: true,
  burmese: true,
  korean: true,
  lao: true,
  norwegian: false,
  polish: false,
  portuguese: false,
  russian: true,
  spanish: false,
  swedish: false,
  thai: true,
  turkish: false,
  urdu: true,
  vietnamese: false,
};
